name: Java Maven Build

# (a) Workflow é executado sempre que há push para a branch principal
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish JAR
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3️⃣ Build Maven (.jar)
      - name: Build with Maven
        run: mvn clean package

      # 4️⃣ Opcional: copiar o .jar para a raiz do repositório
      - name: Copy JAR to root
        run: cp target/*.jar .

      # 5️⃣ Publicar artefacto (.jar)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar
